version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: kasuff2-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./Database/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo-data:
