services:
  mongodb:
    image: mongo:latest
    container_name: kausuff2_mongo
    # No ports exposed
    ports:
      - "27017:27017"
    volumes:
      - ./Database:/data/db
      - ./mongo-init/:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - internal
      - external


networks:
  internal:
    internal: true
  external:
    external: false
