version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: kausuff2_mongo
    # No ports exposed
    volumes:
      - ./Database:/data/db
      - ./mongo-init/:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - internal

  backend:
    build:
      context: .
      dockerfile: ./Backend/Dockerfile
    # No ports exposed
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - internal

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
    networks:
      - internal
      - external

networks:
  internal:
    internal: true
  external:
    external: false
