services:
  mongodb:
    image: mongo:latest
    container_name: kausuff2_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./Database:/data/db
      - ./mongo-init/:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      #healthcheck:
      # test: [ "CMD", "mongo", "admin", "--username", "root", "--password", "example", "--eval", "db.adminCommand('ping').ok" ]
      #interval: 10s
      #timeout: 5s
      #retries: 5
      #start_period: 40s  # Wait for 40 seconds before starting health checks

  backend:
    build:
      context: .
      dockerfile: ./Backend/Dockerfile
    ports:
      - "8080:2608"
    depends_on:
        - mongodb
      #mongodb:
      #condition: service_healthy
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/kasuff2?authSource=admin
