version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: kausuff2_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./Database:/data/db   # Mounts your db folder for MongoDB data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongodb_data:
