export const stupidQuotes = [
    "You blink about 20 times a minute. Impressive, considering how little else you accomplish.",
    "Humans are the only species that blush. Except you, apparently. Emotionless much?",
    "It’s impossible to lick your own elbow. But you're still going to try, aren’t you?",
    "The average human walks the equivalent of five times around the world in their lifetime. You? Probably just to the fridge and back.",
    "Your feet have 250,000 sweat glands. Explains a lot, doesn’t it?",
    "Cows have regional accents. You barely have a personality.",
    "In Switzerland, it’s illegal to own just one guinea pig. But hey, no law against having zero friends!",
    "Your body has enough iron to make a small nail. Too bad it doesn’t have enough motivation to get anything done.",
    "A single strand of hair can hold 3 ounces of weight. Shame your willpower isn’t as strong.",
    "The average person spends 26 years of their life sleeping. You’re already ahead of schedule.",
    "The longest hiccuping spree lasted 68 years. And it was still more productive than your week.",
    "A duck's quack doesn't echo. Your opinions probably shouldn’t either.",
    "Sea otters hold hands while they sleep so they don’t drift apart. Something you’ll never have to worry about.",
    "Sloths can hold their breath longer than dolphins. But you can barely hold a conversation.",
    "Bees can fly higher than Mount Everest. You can’t even get out of bed on time.",
    "Humans shed about 40 pounds of skin in their lifetime. You? Still managing to flake on plans.",
    "You share 60% of your DNA with a banana. Finally, something that explains a lot.",
    "An average cloud weighs 1.1 million pounds. You feel attacked yet?",
    "Your body replaces every particle every seven years. Too bad it didn’t replace your bad decisions.",
    "Most wasabi isn’t real wasabi. Kinda like your confidence.",
    "Sharks existed before trees. But neither will remember you.",
    "Wombat poop is cube-shaped. Unlike your life, which is just a mess.",
    "Octopuses have three hearts. You barely have one.",
    "Honey never spoils. Unlike that attitude of yours.",
    "A bolt of lightning contains enough energy to toast 100,000 slices of bread. You’re still burning your toast though, aren’t you?",
    "Butterflies can taste with their feet. And yet, you still can’t find a good taste in music.",
    "A day on Venus is longer than a year. Luckily, your bad decisions don't take that long.",
    "A single teaspoon of honey represents the lifetime work of 12 bees. Meanwhile, you’re here doing... whatever this is.",
    "It takes 8 minutes for sunlight to reach Earth. Kinda like how long it takes for your brain to catch up during conversations.",
    "Pineapples take two years to grow. That’s still faster than your problem-solving skills.",
    "Koalas sleep up to 22 hours a day. At least they're cute, what’s your excuse?"
];
